services:
  localstack:
    container_name: localstack_sandbox
    image: localstack/localstack:3.4.0   # FIXED: Pinned to a rock-solid, stable version
    ports:
      - "4566:4566"
    environment:
      - SERVICES=ec2,s3
      - AWS_DEFAULT_REGION=ap-south-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always

 # ADDING REDIS TASK BROKER FOR CELERY
  redis_broker:
    container_name: redis_task_broker
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
